### ISSUE TITLE
license scope

### ISSUE THREAD

**Issue by jigneshmpatel** [igia/igia-keycloak#37]
I am trying to understand the scope of the license, is this under the fee scope  for the commercial use.

**Comment by jigneshmpatel** [comment]
also what java version it is uses. For sure it fails for Java 8.

**Comment by mfoates** [comment]
See [license summary](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) for questions regarding use of MPL2 licensed code. Implications depend on your usage.

The software was originally developed using Java 7.

**Comment by mfoates** [comment]
Actually this repo uses Java 8 not Java 7. It probably fails due to an old Key Cloak version.
